units_dict_case_sensitive = {
 'MJ': 'megajoules',
 'MN': 'meganewtons',
 'MPa': 'megapascals',
 'MT': 'megatonnes',
 'MW': 'megawatts',
 'MWh': 'megawatt-hours',
 'Mcal': 'megacalories',
 'Mdyn': 'megadynes',
 'MeV': 'megaelectronvolts',
 'Merg': 'megaergs',
 'Mm': 'megameters',
 'MtTNT': 'megatonne of tee en tee',
 'MtonTNT': 'megaton of tee en tee',
 'Nm': 'newton meters',
 'mJ': 'millijoules',
 'mN': 'millinewtons',
 'mPa': 'millipascals',
 'mb': 'millibars',
 'mbar': 'millibars',
 'mcal': 'millicalories',
 'mdyn': 'millidynes',
 'meV': 'millielectronvolts',
 'mg': 'milligrams',
 'mgf': 'milligram force',
 'mi': 'miles',
 'ml': 'millilitres',
 'mm': 'millimeters',
 'mmHg': 'millimeters of mercury',
 'nJ': 'nanojoules',
 'nN': 'nanonewtons',
 'nm': 'nanometers',
 'B': 'billion',
 'M': 'million',
 'N': 'newtons',
 'T': 'trillion',
 'b': 'bytes',
 'j': 'joules',
 'm': 'meters',
 't': 'tonnes',
 'g': 'grams',
}

units_dict = { 
 'btu': 'British thermal unit',
 'gn': 'giganewtons',
 'gttnt': 'gigatonne of tee en tee',
 'gtontnt': 'gigaton of tee en tee',
 'lt': 'long tons',
 'ltf': 'long ton force',
 'stf': 'short ton force',
 'tw': 'terawatts',
 'twh': 'terawatt-hours',
 'torr': 'torrs',
 'usbbl': 'U S barrels',
 'usbeerbbl': 'U S beer barrels',
 'usbsh': 'U S bushels',
 'usbu': 'U S bushels',
 'usdrybbl': 'U S dry barrels',
 'usdrygal': 'U S dry gallons',
 'usdrypt': 'U S dry pints',
 'usdryqt': 'U S dry quarts',
 'usgal': 'U S gallons',
 'usoz': 'U S fluid ounces',
 'uspt': 'U S pints',
 'usqt': 'USquarts',
 'acre': 'acres',
 'atm': 'atmospheres',
 'au': 'astronomical units',
 'cal': 'calories',
 'cc': 'cubic centimeters',
 'cj': 'centijoules',
 'cl': 'centilitres',
 'cm': 'centimeters',
 'cufoot': 'cubic foots',
 'cufootnaturalgas': 'cubic foot of natural gas',
 'cuft': 'cubic foots',
 'cuftnaturalgas': 'cubic foot of natural gas',
 'cuin': 'cubic inches',
 'cuyd': 'cubic yards',
 'daj': 'decajoules',
 'dbar': 'decibars',
 'degc': 'degree celsius',
 'degf': 'degree fahrenheit',
 'degr': 'degrees rankine',
 'dj': 'decijoules',
 'drachm': 'drachms',
 'dram': 'drachms',
 'dunam': 'dunams',
 'dyn': 'dynes',
 'dyne': 'dynes',
 'eb': 'exabytes',
 'erg': 'ergs',
 'ev': 'electronvolts',
 'ft': 'feet',
 'ftlbf': 'foot-pounds force',
 'ftpdl': 'foot-poundal',
 'furlong': 'furlongs',
 'gb': 'gigabytes',
 'gev': 'gigaelectronvolts',
 'gf': 'gram force',
 'gj': 'gigajoules',
 'gpa': 'gigapascals',
 'gr': 'grains',
 'grf': 'grain force',
 'gw': 'gigawatts',
 'gwh': 'gigawatt-hours',
 'ha': 'hectares',
 'hj': 'hectojoules',
 'hp': 'horsepower',
 'hpa': 'hectopascals',
 'hph': 'horsepower-hour',
 'impbbl': 'imperial barrels',
 'impbsh': 'imperial bushels',
 'impbu': 'imperial bushels',
 'impfloz': 'imperial fluid ounces',
 'impgal': 'imperial gallons',
 'impgalatm': 'imperial gallon atmosphere',
 'impoz': 'imperial fluid ounces',
 'imppt': 'imperial pints',
 'impqt': 'imperialquarts',
 'in': 'inches',
 'inhg': 'inch of mercurys',
 'inlbf': 'inch-pounds force',
 'inozf': 'inch-ounce force',
 'kn': 'kilonewtons',
 'kb': 'kilobytes',
 'kba': 'kilobaryes',
 'kcal': 'kilocalories',
 'kdyn': 'kilodynes',
 'kerg': 'kiloergs',
 'kev': 'kiloelectronvolts',
 'kg': 'kilograms',
 'kgf': 'kilogram force',
 'kj': 'kilojoules',
 'kl': 'kilolitres',
 'km': 'kilometers',
 'kn': 'knots',
 'kpa': 'kilopascals',
 'kt': 'kilotonnes',
 'kttnt': 'kilotonne of tee en tee',
 'ktontnt': 'kiloton of tee en tee',
 'kw': 'kilowatts',
 'kwh': 'kilowatt-hours',
 'latm': 'litre atmospheres',
 'lb': 'pounds',
 'lbf': 'pounds force',
 'ly': 'light-years',
 'mpgimp': 'miles per imperial gallon',
 'mpgus': 'miles per yoo aesse gallon',
 'mph': 'miles per hour',
 'nmi': 'nautical miles',
 'oilbbl': 'barrels',
 'oz': 'ounces',
 'ozt': 'troy ounces',
 'pa': 'pascals',
 'pb': 'petabytes',
 'pc': 'parsecs',
 'pdl': 'poundals',
 'psi': 'pound per square inche',
 'ry': 'rydbergs',
 'sqfoot': 'square feet',
 'sqft': 'square feet',
 'sqin': 'square inches',
 'sqmi': 'square miles',
 'sqnmi': 'square nautical miles',
 'sqyd': 'square yards',
 'ttnt': 'tonne of tee en tee',
 'tb': 'terabytes',
 'tf': 'tonne force',
 'tontnt': 'ton of tee en tee',
 'tsubo': 'tsubos',
 'usfloz': 'U S fluid ounces',
 'usgalatm': 'yoo aesse gallon atmosphere',
 'yb': 'yottabytes',
 'yd': 'yards',
 'zb': 'zettabytes',
 'μN': 'micronewtons',
 'μg': 'micrograms',
 'μn': 'micronewtons',
 'μg': 'micrograms',
 'μj': 'microjoules',
 'μm': 'micrometers',
 'l': 'litres',
 'w': 'watts',
 'wh': 'watt-hours',
 'å': 'angstroms',
}

units_dict_special =  {
 '$/kg': 'dollars per kilogram',
 '$/lb': 'dollars per pound',
 '$/ozt': 'dollars pertroy ounce',
 '%': 'percent',
 '/acre': 'per acre',
 '/ha': 'per hectare',
 '/km²': 'per square kilometer',
 '/sqmi': 'per square mile',
 'c-change': 'Celsius changes',
 'f-change': 'Fahrenheit changes',
 'lt-f': 'long ton force',
 'mw.h': 'megawatt-hours',
 'n.m': 'newton meters',
 'pd/km²': 'inhabitants per square kilometer',
 'pd/sqmi': 'inhabitants per square mile',
 'st-f': 'short ton force',
 'tw.h': 'terawatt-hours',
 'u.s.gal/mi': 'yoo aesse gallons per mile',
 'cm²': 'square centimeters',
 'cm³': 'cubic centimeters',
 'foot/s': 'feet per second',
 'ft/s': 'feet per second',
 'ft²': 'square feet',
 'ftlb-f': 'foot-pounds force',
 'g-f': 'gram-forces',
 'g/m³': 'gram per cubic meter',
 'gr-f': 'grain force',
 'gw.h': 'gigawatt-hours',
 'impgal/mi': 'imperial gallons per mile',
 'inlb-f': 'inch-pounds force',
 'inoz-f': 'inch-ounce force',
 'kg-f': 'kilogram force',
 'kg.m': 'kilogram meters',
 'kg/m³': 'kilogram per cubic meter',
 'kgf.m': 'kilogram force-meters',
 'km/h': 'kilometers per hour',
 'km/l': 'kilometers per litre',
 'km²': 'square kilometers',
 'kw.h': 'kilowatt-hours',
 'l/100km': 'litres per hundred kilometer',
 'l/km': 'litres per kilometer',
 'lb-f': 'pounds force',
 'lb.ft': 'pound force-foots',
 'lb/ft³': 'pound per cubic foot',
 'lb/yd³': 'pound per cubic yard',
 'lbf.ft': 'pound force-foots',
 'm/s': 'meters per second',
 'km/s': 'kilometers per second',
 'm²': 'square meters',
 'm³': 'cubic meters',
 'mg-f': 'milligram force',
 'mm²': 'square millimeters',
 'mm³': 'cubic millimeters',
 'mpgU.S': 'miles per yoo aesse gallon',
 'pd/acre': 'inhabitants per acre',
 'pd/ha': 'inhabitants per hectare',
 't-f': 'tonne force',
 'usgal/mi': 'yoo aesse gallons per mile',
 'w.h': 'watt-hours',
 'yd²': 'square yards',
 '°c': 'degree celsius',
 '℃': 'degree celsius',
 '°f': 'degree fahrenheit',
 '℉': 'degree fahrenheit',
 '°r': 'degrees rankine',
 '°ra': 'degrees rankine'
}
