import re

_abbreviations = [(re.compile('\\b%s\\.' % x[0], re.IGNORECASE), x[1]) for x in [
#_abbreviations = [(re.compile('\\b%s\\.?[^a-z]' % x[0],re.IGNORECASE),x[1]) for x in [
#_abbreviations = { 
    ('mrs.', 'misess'),
    ('ms.','miss'),
    ('mr.','mister'),
    ('dr.','doctor'),
    ('st.','street'),
    ('ave.','avenue'),
    ('co.','company'),
    ('jr.','junior'),
    ('sr.','senior'),
    ('fr.','father'),
    ('maj.','major'),
    ('gen.','general'),
    ('drs.','doctors'),
    ('rev.','reverend'),
    ('lt.','lieutenant'),
    ('hon.','honorable'),
    ('sgt.','sergeant'),
    ('capt.','captain'),
    ('esq.','esquire'),
    ('ltd.','limited'),
    ('col.','colonel'),
    ('sq.','square'),
    ('approx.','approximately'),
    ('apt.','apartments'),
    ('dept.','department'),
    ('no.','number'),
    ('tel.','telephone'),
    ('temp.','temperature'),
    ('vs.','versus'),
    ('vol.','volume'),
    ('tsp.','teaspoons'),
    ('tbs.','tablespoons'),
    ('tbsp.','tablespoons'),
    ('pt.','pint'),
    ('qt.','quart'),
    ('ln.','lane'),
    ('rd.','road'),
    ('BA.','bachelor of arts'),
    ('B.A.','bachelor of arts'),
    ('BS.','bachelor of science'),
    ('B.S.','bachelor of science'),
    ('mon','monday'),
    ('tues','tuesday '),
    ('wed','wednesday'),
    ('thurs','thursday'),
    ('fri','friday'),
    ('sat','saturday'),
    ('sun','sunday'),
    ('abbrev.','abbreviation'),
    #'cent','century'),
    ('chap.','chapter'),
    ('ch.','chapter'),
    #'us ','the united states '),
    #'u.s. ','the united states '),
    #'usa ','the united states of america '),
    #'u.s.a. ','the united states of america '),
    ('ai.','aey ai'),
    ('a.i.','aey ai'),
#}
]]
